### ISSUE TITLE
PromiseFuture from Promise on fulfill

### ISSUE THREAD

**Issue by vjkoskela** [groupon/promise#4]
The Javadoc example in Promise.java shows that the fulfill method returns a PromiseFuture. While the PromiseImpl has an internalFulfill which does return such an instance the fulfill method on the interface does not return anything. Is this an oversight or is there another recommended way to get the future to a fulfilled promise?

**Comment by fsiegrist42** [comment]
It looks like the Javadoc was not updated to match the expected behavior.  The PromiseFuture was functionally replaced by the after() method.  I will take a look at updating the documentation.

**Comment by vjkoskela** [comment]
Thanks. How does using after get you the promise future?

**Comment by fsiegrist42** [comment]
Calling after() returns a Promise<Void> which means you can do the following:

Promise<String> doStuff = new PromiseImpl<>();
Promise<Void> afterPromise = doStuff.after();
afterPromise.then(success -> ..., failure -> ...);
doStuff.fulfill("string");

Since the after() returns a promise it allows you to process the result of the chain the same as you would any promise.

**Comment by vjkoskela** [comment]
Got it. So for all intensive purposes `PromiseFuture` is not used outside the library implementation (I guess that's what I'm really asking here).

**Comment by vjkoskela** [comment]
I think we figured it out. Thanks.
